export const ROUTES = {
  default: `/`,
  pageNotFound: `/404`,
  signIn: `/signIn`,
  changePassword: `/changePassword`,
  forgotPassword: `/forgotPassword`,
  resetPassword: (token: any) => `/resetPassword/${token}`,
  dashboard: `/dashboard`,
  vendorDutyAnalytics: `/vendor-duty-analytics`,
  vendorLeadsAnalytics: `/vendor-leads-analytics`,
  userManagement: `/user-management`,
  userList: `/user-management/list`,
  userView: `/user-management/:id`,
  userEdit: `/user-management/:id/edit`,
  privacyPolicy: `/privacy-policy`,
  termsAndConditions: `/terms-and-conditions`,
  termsAndConditionsVendor: `/terms-and-conditions-vendor`,
  categoryManagement: `/category-management`,
  addCategory: `/category-management/add`,
  editCategory: (_id: string | number) => `/category-management/edit/${_id}`,
  viewCategory: (_id: string | number) => `/category-management/view/${_id}`,
  serviceManagement: `/service-management`,
  addService: `/service-management/add`,
  editService: (_id: string | number) => `/service-management/edit/${_id}`,
  viewService: (_id: string | number) => `/service-management/view/${_id}`,
  cityManagement: `/city-management`,
  addCity: `/city-management/add`,
  editCity: (_id: string | number) => `/city-management/edit/${_id}`,
  viewCity: (_id: string | number) => `/city-management/view/${_id}`,
  cityAreaManagement: `/city-area-management`,
  addCityArea: `/city-area-management/add`,
  editCityArea: (_id: string | number) => `/city-area-management/edit/${_id}`,
  viewCityArea: (_id: string | number) => `/city-area-management/view/${_id}`,
  cityCategoryManagement: `/city-category-management`,
  addCityCategory: `/city-category-management/add`,
  editCityCategory: (_id: string | number) => `/city-category-management/edit/${_id}`,
  viewCityCategory: (_id: string | number) => `/city-category-management/view/${_id}`,
  addFaq: `/faq-management/add`,
  faqManagement: `/faq-management`,
  viewFaq: (_id: string | number) => `/faq-management/edit/${_id}`,
  editFaq: (_id: string | number) => `/faq-management/view/${_id}`,
  contactUsManagement: `/contactUs-management`,
  viewContactUs: (_id: string | number) => `/contactUs-management/view/${_id}`,
  editContactUs: (_id: string | number) => `/contactUs-management/edit/${_id}`,
  trainingManagement: `/training-management`,
  insurance: `/insurance`,
  addTraining: `/training-management/add`,
  viewTraining: (_id: string | number) => `/training-management/view/${_id}`,
  editTraining: (_id: string | number) => `/training-management/edit/${_id}`,
  vendorManagement: `/vendor-management`,
  addVendor: `/vendor-management/add`,
  editVendor: (_id: string | number) => `/vendor-managements/edit/${_id}`,
  viewVendor: (_id: string | number) => `/vendor-managements/view/${_id}`,
  customerManagement: `/customer-management`,
  addCustomer: `/customer-management/add`,
  editCustomer: `/customer-management/edit`,
  viewCustomer: (_id: string | number) => `/customer-management/view/${_id}`,
  addCitySeoManagement: `/city-seo-management`,
  addAllSeoManagement: `/all-seo-management`,
  addCategorySeoManagement: `/category-seo-management`,
  addCityAreaSeoManagement: `/city-area-seo-management`,
  addCityCategorySeoManagement: `/city-category-seo-management`,
  addCategoryServiceSeoManagement: `/category-service-seo-management`,
  addCityCategoryServiceSeoManagement: `/city-category-service-seo-management`,
  addCityAreaCategorySeoManagement: `/city-area-category-seo-management`,
  addCityAreaCategoryServiceSeoManagement: `/city-area-category-service-seo-management`,
  subCategoryManagement: `/sub-category-management`,
  addSubCategory: `/sub-category-management/add`,
  editSubCategory: (_id: string | number) => `/sub-category-management/edit/${_id}`,
  viewSubCategory: (_id: string | number) => `/sub-category-management/view/${_id}`,
  subServiceManagement: `/sub-service-management`,
  addSubService: `/sub-service-management/add`,
  editSubService: (_id: string | number) => `/sub-service-management/edit/${_id}`,
  viewSubService: (_id: string | number) => `/sub-service-management/view/${_id}`,
  bookingManagement: `/booking-management`,
  vendorPaymentManagement: `/vendor-payment-management`,
  viewBooking: (_id: string | number) => `/booking-management/view/${_id}`,
  viewVendorPayment: (_id: string | number) => `/vendor-payment-management/view/${_id}`,
  reviewManagement: `/review-management`,
  addReview: `/review-management/add`,
  viewReview: (_id: string | number) => `/review-management/view/${_id}`,
  editReview: (_id: string | number) => `/review-management/edit/${_id}`,
  couponManagement: `/coupon-management`,
  addCoupon: `/coupon-management/add`,
  viewCoupon: (_id: string | number) => `/coupon-management/view/${_id}`,
  editCoupon: (_id: string | number) => `/coupon-management/edit/${_id}`,
  dynamicPath: (path: string) => `/static-path/${path}`,
  aboutUs: `/about-us`,
  paymentHistoryManagement: `/payment-history-management`,
  viewPaymentHistory: (_id: string | number) => `/payment-history-management/view/${_id}`,
  subAdminManagement: `/sub-admin-management`,
  addSubAdmin: `/sub-admin/add`,
  editSubAdmin: (_id: string | number) => `/sub-admin/edit/${_id}`,
  viewSubAdmin: (_id: string | number) => `/sub-admin/view/${_id}`,
  videoManagement: `/video-management`,
  addVideo: `/video-management/add`,
  editVideo: (_id: string | number) => `/video-management/edit/${_id}`,
  viewVideo: (_id: string | number) => `/video-management/view/${_id}`,
  homeBannerManagement: `/home-banner-management`,
  addHomeBanner: `/home-banner-management/add`,
  editHomeBanner: (_id: string | number) => `/home-banner-management/edit/${_id}`,
  viewHomeBanner: (_id: string | number) => `/home-banner-management/view/${_id}`,
  supportTicket: `/support-ticket-management`
};
