sonar.host.url=https://sonarqube.agiletechnologies.in
sonar.projectKey=sqp_1a255335dfdad2805ffedf4b089ceac565de78b2-master
sonar.projectName=reactjs-admin-number-dekho

# Comma-separated paths to directories with sources (required)
sonar.sources=.
sonar.verbose=true
sonar.inclusions=
sonar.exclusions=node_modules/*
sonar.test.exclusions=
sonar.analysis.buildNumber=121
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/coverage.html

# Language
sonar.language=nodejs

# Encoding of the source files
sonar.sourceEncoding=UTF-8
