sonar.host.url=https://sonarqube.agiletechnologies.in
sonar.projectKey=sqp_b81017cbbcfb1b34f8cb387a50cc862db8d9bdfe (masters)
sonar.projectName=react-native-msr-ho-master


# Comma-separated paths to directories with sources (required)
sonar.sources=.
sonar.verbose=true
sonar.inclusions=
#sonar.exclusions=**/*.java,src/custom-package/*
sonar.exclusions=**/__tests__/**,**/*.test.js,node_modules/*
sonar.test.exclusions=
sonar.analysis.buildNumber=121
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/coverage.html
# Language
#sonar.language=nodejs
sonar.language=js
# Encoding of the source files
sonar.sourceEncoding=UTF-8