/* Query key constants for react-query hooks */
export const QueryKeys = {
  getResourceType: 'getResourceType',
  getCms: 'getCms',
  getListWithFaqPagination: 'getListWithFaqPagination',
  getNotificationList: 'getNotificationList',
  getConfig: 'getConfig',
  listHorse: 'listHorse',
  getUserProfile: 'getUserProfile',
  getAutoCompleteAddressList: 'getAutoCompleteAddressList',
  getTrips: 'getTrips',
  quetosListPending: 'quetosListPending',
  quetosListReceived: 'quetosListReceived',
  quetosListDecline: 'quetosListDecline',
  quetosDetails: 'quetosDetails',
  NotificationList: 'NotificationList',
};

export const MutationQueryKeys = {
  loginMutate: 'loginMutate',
  signupMutate: 'signupMutate',
  fileUploadMutate: 'fileUploadMutate',
  markAsReadMutate: 'markAsReadMutate',
  signInMutate: 'signInMutate',
  forgotPasswordMutate: 'forgotPasswordMutate',
  addHorseMutate: 'addHorseMutate',
  deleteHorseMutate: 'deleteHorseMutate',
  listHorse: 'listHorse',
  profileMutate: 'profileMutate',
  logOutMutate: 'logOutMutate',
  changePasswordMutate: 'changePasswordMutate',
  addressDetailMutate: 'addressDetailMutate',
  createTripMutate: 'createTripMutate',
  getTrips: 'getTrips',
  acceptQuotation: 'acceptQuotation',
  pendingQuotation: 'pendingQuotation',
  declineQuotation: 'declineQuotation',
  rejectQuotation: 'rejectQuotation',
  rejectAllQuotation: 'rejectAllQuotation',
  quotationReSubmit: 'quotationReSubmit',
  editTripRequest: 'editTripRequest',
  addReview: 'addReview',
  deleteAllNotification: 'deleteAllNotification',
  deleteNotification: 'deleteNotification',
  unReadNotification: 'unReadNotification',
  toggleNotification: 'toggleNotification',
  HorseListForTrip: 'HorseListForTrip',
};
