/* defined all the screen and common test key constants */

export const SignInTestKeys = {
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  EMAIL: 'EMAIL',
  PASSWORD: 'PASSWORD',
  SIGN_IN: 'SIGN_IN',
  INPUT_EMAIL_ERROR: 'INPUT_EMAIL_ERROR',
  INPUT_PASSWORD_ERROR: 'INPUT_PASSWORD_ERROR',
};
export const SignUpTestKeys = {
  CREATE_ACCOUNT_SCREEN: 'CREATE_ACCOUNT_SCREEN',
  FIRST_NAME: 'FIRST_NAME',
  LAST_NAME: 'LAST_NAME',
  EMAIL: 'EMAIL',
  PASSWORD: 'PASSWORD',
  CONFIRM_PASSWORD: 'CONFIRM_PASSWORD',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  INPUT_FIRST_NAME_ERROR: 'INPUT_FIRST_NAME_ERROR',
  INPUT_LAST_NAME_ERROR: 'INPUT_LAST_NAME_ERROR',
  INPUT_EMAIL_ERROR: 'INPUT_EMAIL_ERROR',
  INPUT_PASSWORD_ERROR: 'INPUT_PASSWORD_ERROR',
  INPUT_CONFIRM_PASSWORD_ERROR: 'INPUT_CONFIRM_PASSWORD_ERROR',
};
export const ForgotPasswordTestKeys = {
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  BACK: 'BACK',
  HEADER_TEXT: 'HEADER_TEXT',
  EMAIL: 'EMAIL',
  CONTINUE: 'CONTINUE',
  EMAIL_ERROR: 'EMAIL_ERROR',
};
export const AppCommonTestKeys = {
  CONTAINER_VIEW: 'CONTAINER_VIEW',
  HEADER_TITLE: 'HEADER_TITLE',
  HEADER_LEFT_BUTTON: 'HEADER_LEFT_BUTTON',
  HEADER_RIGHT_BUTTON: 'HEADER_RIGHT_BUTTON',
  MULTI_PICKER_TEST_ID: 'MULTI_PICKER_TEST_ID',
  MULTI_PICKER_ERROR_TEST_ID: 'MULTI_PICKER_ERROR_TEST_ID',
};

export const HomeScreenTestKeys = {
  HOME_SCREEN: 'HOME_SCREEN',
  NAME: 'NAME',
  NOTES: 'NOTES',
  PICK_UP_DATE: 'PICK_UP_DATE',
  PICK_UP_ADDRESS: 'PICK_UP_ADDRESS',
  DROP_UP_ADDRESS: 'DROP_UP_ADDRESS',
  RETURN_PICK_UP_DATE: 'RETURN_PICK_UP_DATE',
  RETURN_PICK_UP_ADDRESS: 'RETURN_PICK_UP_ADDRESS',
  RETURN_DROP_UP_ADDRESS: 'RETURN_DROP_UP_ADDRESS',
  SCROLL_PICK_UP: 'SCROLL_PICK_UP',
  SCROLL_DROP: 'SCROLL_DROP',
  ROUND_PICK_UP: 'ROUND_PICK_UP',
  ROUND_DROP: 'ROUND_DROP',
  SINGLE_TRIP_BUTTON: 'SINGLE_TRIP_BUTTON',
  ROUND_TRIP_BUTTON: 'ROUND_TRIP_BUTTON',
  SEPARATE_VIEW: 'SEPARATE_VIEW',
};

export const MyTripsTestKeys = {
  MY_TRIPS_SCREEN: 'MY_TRIPS_SCREEN',
  TRIP_TAB: 'TRIP_TAB',
  TRIP_LIST: 'TRIP_LIST',
  EMPTY_TRIP: 'EMPTY_TRIP',
  TRIP_ITEM: 'TRIP_ITEM',
  SEARCH: 'SEARCH',
  TRIP_STATUS: 'TRIP_STATUS',
  TRIP_TYPE: 'TRIP_TYPE',
  TRIP_DATE: 'TRIP_DATE',
  TRIP_PICKUP: 'TRIP_PICKUP',
  TRIP_DROP: 'TRIP_DROP',
  TRIP_VIEW: 'TRIP_VIEW',
};

export const TripDetailTestKeys = {
  TRIP_DETAIL_SCREEN: 'TRIP_DETAIL_SCREEN',
  TRIP_STATUS: 'TRIP_STATUS',
  TRIP_TYPE: 'TRIP_TYPE',
  TRIP_DATE: 'TRIP_DATE',
  TRIP_PICKUP: 'TRIP_PICKUP',
  TRIP_DROP: 'TRIP_DROP',
  CANCEL_TRIP: 'CANCEL_TRIP',
  TRANSPORT_DETAILS: 'TRANSPORT_DETAILS',
  INCIDENT_REPORT: 'INCIDENT_REPORT',
  TRIP_UPDATE: 'TRIP_UPDATE',
};
export const QuetosScreenTestKeys = {
  QUETOS_SCREEN: 'QUETOS_SCREEN',
  TITLE: 'TITLE',
  SEARCH: 'SEARCH',
  STATUS_LIST: 'STATUS_LIST',
  QUETOS_PENDING_LIST: 'QUETOS_PENDING_LIST',
  QUETOS_RECEIVED_LIST: 'QUETOS_RECEIVED_LIST',
  QUETOS_DECLINE_LIST: 'QUETOS_DECLINE_LIST',
};
export const QuetosDetailsScreenTestKeys = {
  QUETOS_DETAILS_SCREEN: 'QUETOS_DETAILS_SCREEN',
  COLLAPSE_VIEW: 'COLLAPSE_VIEW',
  EXPAND_VIEW: 'EXPAND_VIEW',
  TRIP_NAME: 'TRIP_NAME',
  PICK_UP_DATE: 'PICK_UP_DATE',
  TRIP_TYPE: 'TRIP_TYPE',
  PICK_UP_LOCATION: 'PICK_UP_LOCATION',
  DROP_UP_LOCATION: 'DROP_UP_LOCATION',
  TRAILER_TYPE: 'TRAILER_TYPE',
  HORSES: 'HORSES',
  NOTES: 'NOTES',
};

export const EditProfileDetailsScreen = {
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN',
  EDIT_PROFILE_NAME: 'EDIT_PROFILE_NAME',
  EDIT_PROFILE_NOTES: 'EDIT_PROFILE_NOTES',
  EDIT_PROFILE_PICK_UP_DATE: 'EDIT_PROFILE_PICK_UP_DATE',
  EDIT_PROFILE_PICK_UP_ADDRESS: 'EDIT_PROFILE_PICK_UP_ADDRESS',
  EDIT_PROFILE_DROP_UP_ADDRESS: 'EDIT_PROFILE_DROP_UP_ADDRESS',
  EDIT_PROFILE_RETURN_PICK_UP_DATE: 'EDIT_PROFILE_RETURN_PICK_UP_DATE',
  EDIT_PROFILE_RETURN_PICK_UP_ADDRESS: 'EDIT_PROFILE_RETURN_PICK_UP_ADDRESS',
  EDIT_PROFILE_RETURN_DROP_UP_ADDRESS: 'EDIT_PROFILE_RETURN_DROP_UP_ADDRESS',
  EDIT_PROFILE_SCROLL_PICK_UP: 'EDIT_PROFILE_SCROLL_PICK_UP',
  EDIT_PROFILE_SCROLL_DROP: 'EDIT_PROFILE_SCROLL_DROP',
  EDIT_PROFILE_ROUND_PICK_UP: 'EDIT_PROFILE_ROUND_PICK_UP',
  EDIT_PROFILE_ROUND_DROP: 'EDIT_PROFILE_ROUND_DROP',
  EDIT_PROFILE_SINGLE_TRIP_BUTTON: 'EDIT_PROFILE_SINGLE_TRIP_BUTTON',
  EDIT_PROFILE_ROUND_TRIP_BUTTON: 'EDIT_PROFILE_ROUND_TRIP_BUTTON',
  EDIT_PROFILE_SEPARATE_VIEW: 'EDIT_PROFILE_SEPARATE_VIEW',
};

export const ReviewScreenTestKeys = {
  REVIEW_SCREEN: 'REVIEW_SCREEN',
  STAR_VIEW: 'STAR_VIEW',
  STAR_NUMBER: 'STAR_NUMBER',
  RATING_ERROR: 'RATING_ERROR',
  DISPLAY_ERROR: 'DISPLAY_ERROR',
  REVIEW_SUBMIT_BUTTON: 'REVIEW_SUBMIT_BUTTON',
};
export const NotificationScreenTestKeys = {
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  DELETE_ALL_BUTTON: 'DELETE_ALL_BUTTON',
  DELETE_ALL_BUTTON_CONFIRM: 'DELETE_ALL_BUTTON_CONFIRM',
};
